"""initial schema

Revision ID: 1090ea2fb38b
Revises: 
Create Date: 2026-07-08 23:55:28.757288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  —— AutoString 类型来自这里


# revision identifiers, used by Alembic.
revision: str = '1090ea2fb38b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cycle',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=True),
    sa.Column('cycle_length', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cycle', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cycle_user_id'), ['user_id'], unique=False)

    op.create_table('memory',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('snippet', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('themes', sa.JSON(), nullable=True),
    sa.Column('event', sa.Text(), nullable=True),
    sa.Column('objects', sa.JSON(), nullable=True),
    sa.Column('triggers', sa.JSON(), nullable=True),
    sa.Column('recovery', sa.JSON(), nullable=True),
    sa.Column('emotions', sa.JSON(), nullable=True),
    sa.Column('expression_style', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('has_action', sa.Boolean(), nullable=False),
    sa.Column('mood', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('llm_raw', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memory_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_user_id'), ['user_id'], unique=False)

    op.create_table('user',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nickname', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_active_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('response',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('responder_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('memory_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('response_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['memory_id'], ['memory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_response_memory_id'), ['memory_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_response_responder_id'), ['responder_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_response_responder_id'))
        batch_op.drop_index(batch_op.f('ix_response_memory_id'))

    op.drop_table('response')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('memory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memory_user_id'))
        batch_op.drop_index(batch_op.f('ix_memory_created_at'))

    op.drop_table('memory')
    with op.batch_alter_table('cycle', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cycle_user_id'))

    op.drop_table('cycle')
    # ### end Alembic commands ###
